### ISSUE TITLE
The build is not minimal

### ISSUE THREAD

**Issue by hgkjshegfskef** [faaxm/exmpl-cmake-grpc#6] opened 2022-03-11 09:53 UTC
`cmake --build <build_dir>` regenerates .proto files on every single invocation, practically triggering a full rebuild of the whole application for no good reason. One way would be to not use `protobuf_generate`, but custom targets/commands. Or perhaps `protobuf_generate` should create custom targets under the hood? It also seems like `protobuf_generate` is an internal undocumented function by protobuf, that happens to be exported into the config file. Perhaps we should not rely on `protobuf_generate` at all?

**Comment by hgkjshegfskef** [comment] 2022-03-12 11:46
Based on the CMake code for route_guide example in gRPC, I came up with the following:
```cmake
# ~~~
# Generates Protobuf and gRPC sources and headers inside CMAKE_CURRENT_BINARY_DIR/prefix.
# - target_name: target to create for generated files.
# - prefix: any additional directory(s) between CMAKE_CURRENT_SOURCE_DIR and .proto files.
# - protos_list: list of paths to .proto files (can be relative to CMAKE_CURRENT_SOURCE_DIR).
# Assumes following CACHE variables exist and are set to correct values:
# - sbal_PROTOC_PATH: Path to protoc executable.
# - sbal_GRPC_CPP_PLUGIN_PATH: Path to grpc_cpp_plugin executable.
# Assumes Protobuf and gRPC IMPORTED targets are defined.
function(sbal_proto_generate target_name prefix protos_list)
    add_library(${target_name})

    foreach(proto IN LISTS protos_list)
        cmake_path(SET proto_path "${proto}") # CMake 3.20+
        cmake_path(ABSOLUTE_PATH proto_path)
        list(APPEND proto_paths "${proto_path}")
        cmake_path(GET proto_path STEM proto_filename)
        list(APPEND pb_sources "${CMAKE_CURRENT_BINARY_DIR}/${prefix}/${proto_filename}.pb.cc")
        list(APPEND pb_headers "${CMAKE_CURRENT_BINARY_DIR}/${prefix}/${proto_filename}.pb.h")
        list(APPEND grpc_sources
             "${CMAKE_CURRENT_BINARY_DIR}/${prefix}/${proto_filename}.grpc.pb.cc")
        list(APPEND grpc_headers
             "${CMAKE_CURRENT_BINARY_DIR}/${prefix}/${proto_filename}.grpc.pb.h")
    endforeach()

    add_custom_command(
        OUTPUT ${pb_sources} ${pb_headers} ${grpc_sources} ${grpc_headers}
        COMMAND
            "$CACHE{sbal_PROTOC_PATH}" --grpc_out "${CMAKE_CURRENT_BINARY_DIR}" --cpp_out
            "${CMAKE_CURRENT_BINARY_DIR}" -I "${CMAKE_CURRENT_SOURCE_DIR}"
            "--plugin=protoc-gen-grpc=$CACHE{sbal_GRPC_CPP_PLUGIN_PATH}" ${proto_paths}
        DEPENDS ${proto_paths}
        USES_TERMINAL)

    target_sources(${target_name} PRIVATE ${pb_sources} ${grpc_sources})
    target_include_directories(${target_name} PUBLIC "${CMAKE_CURRENT_BINARY_DIR}")
    target_link_libraries(${target_name} PUBLIC gRPC::grpc++_reflection gRPC::grpc++
                                                protobuf::libprotobuf)
endfunction()

# Usage:
set(sbal_protocols_list "sbal/route_guide.proto" "sbal/helloworld.proto")
sbal_proto_generate(sbal_protocols sbal "${sbal_protocols_list}")
```

The build is not minimal in regards to deleting a single source of header file, or editing a single .proto file, since all files for all protocols will be regenerated (due to protoc running once for all files), but it is at least minimal in regards to not regenerating all files on every incremental build. Obviously, it can be changed to create a separate target per custom command per one .proto file, but for me this is good enough.

**Comment by faaxm** [comment] 2022-03-12 12:13
I cannot reproduce the issue you describe. Rerunning `cmake --build builddir` does not re-generate any sources for me. In fact, rerunning `Ninja` gives a nice `ninja: no work to do.` message.

Changing a `.proto` file results in only the sources for that one file being re-generated. Perhaps this issue depends on the cmake generator being used? I have tested this on linux and macOS with Ninja and Makefiles.

What makes you think `protobuf_generate` was only an internal function? The protobuf maintainers did accept my PR that extended it to support grpc and they continued to accept other pull requests for features only required by external projects.
If there is an issue, I believe fixing `protobuf_generate` would be the way to go.

**Comment by hgkjshegfskef** [comment] 2022-03-12 12:33
> I cannot reproduce the issue you describe.

Ok, I'll try once again some time later. I'm also running ninja on linux. For now, consider this resolved.

> What makes you think protobuf_generate was only an internal function?

It is not documented.

**Comment by faaxm** [comment] 2022-03-12 13:54
> It is not documented.

I think this is more due to the cmake code being somewhat neglected in the protobuf project and not so much because it is intended to be internal. There have also been a couple of cases where protobuf `master` was broken because changes were merged without adding new source files to the cmake project...

I believe it is worth improving (and probably also documenting) the `protobuf_generate` command in the upstream project in case of issues. From my experience, the protobuf maintainers are welcoming towards changes to their cmake code.

In any case, thanks for looking into this and suggesting improvements! Feel free to reopen the issue if you have new findings or comments 🙂

**Closed by faaxm** 2022-03-12 13:54 UTC
